import LandingLayout from './LandingLayout.jsx';

const LAST_UPDATED = 'June 26, 2026';

const PAGES = {
  terms: {
    title: 'Terms & Conditions',
    sections: [
      {
        heading: '1. Acceptance of Terms',
        body: 'By accessing or using CuentaIQ ("the Service"), you agree to be bound by these Terms & Conditions. If you do not agree, you may not use the Service.',
      },
      {
        heading: '2. Description of Service',
        body: 'CuentaIQ is a cloud-based accounting software platform designed for Philippine small and medium-sized businesses. We provide tools for bookkeeping, payroll, tax compliance, and financial reporting.',
      },
      {
        heading: '3. Account Registration',
        body: 'You must provide accurate and complete information when creating an account. You are responsible for maintaining the confidentiality of your credentials and for all activities that occur under your account.',
      },
      {
        heading: '4. Subscription & Payment',
        body: 'Subscriptions are billed as agreed at signup (monthly or annually). All fees are in US Dollars unless otherwise stated. We reserve the right to modify pricing with 30 days\' notice.',
      },
      {
        heading: '5. Acceptable Use',
        body: 'You agree not to misuse the Service — including attempting to gain unauthorised access, transmitting harmful code, or using the Service for any unlawful purpose.',
      },
      {
        heading: '6. Data Ownership',
        body: 'You retain full ownership of all financial data you enter into CuentaIQ. We do not sell, share, or use your business data for any purpose beyond operating the Service.',
      },
      {
        heading: '7. Limitation of Liability',
        body: 'CuentaIQ is provided "as is." To the maximum extent permitted by law, we shall not be liable for any indirect, incidental, or consequential damages arising from your use of the Service.',
      },
      {
        heading: '8. Termination',
        body: 'Either party may terminate the subscription at any time. Upon termination, your data will be available for export for 30 days before permanent deletion.',
      },
      {
        heading: '9. Governing Law',
        body: 'These Terms are governed by the laws of the Republic of the Philippines. Any disputes shall be resolved in the courts of the Philippines.',
      },
      {
        heading: '10. Contact',
        body: 'For questions about these Terms, contact us at hello@cuentaiq.com.',
      },
    ],
  },

  privacy: {
    title: 'Privacy Policy',
    sections: [
      {
        heading: '1. Information We Collect',
        body: 'We collect information you provide directly (name, email, company details, financial data) and technical data generated by your use of the Service (log data, IP address, browser type).',
      },
      {
        heading: '2. How We Use Your Information',
        body: 'We use your information to operate and improve the Service, send transactional emails, respond to support requests, and comply with legal obligations. We do not sell your personal data.',
      },
      {
        heading: '3. Data Storage & Security',
        body: 'Each client\'s data is stored in a dedicated database. We use industry-standard encryption at rest and in transit. Access is restricted to authorised personnel only.',
      },
      {
        heading: '4. Data Retention',
        body: 'We retain your data for as long as your account is active. After termination, data is retained for 30 days to allow export, then permanently deleted.',
      },
      {
        heading: '5. Third-Party Services',
        body: 'We use trusted third-party providers (hosting, email, payment processing) who are bound by confidentiality agreements. We do not share your data with advertisers.',
      },
      {
        heading: '6. Your Rights',
        body: 'You have the right to access, correct, or delete your personal data at any time. To exercise these rights, contact us at hello@cuentaiq.com.',
      },
      {
        heading: '7. Cookies',
        body: 'We use strictly necessary cookies to maintain your session. We do not use advertising or tracking cookies.',
      },
      {
        heading: '8. Changes to This Policy',
        body: 'We may update this Privacy Policy from time to time. We will notify you of significant changes via email or an in-app notice.',
      },
      {
        heading: '9. Contact',
        body: 'For privacy-related concerns, contact us at hello@cuentaiq.com.',
      },
    ],
  },

  refund: {
    title: 'Refund Policy',
    sections: [
      {
        heading: '1. Pioneer Program',
        body: 'The one-time setup fee for the Pioneer Program is non-refundable once onboarding has begun. Monthly subscription fees paid after the free trial period are non-refundable.',
      },
      {
        heading: '2. Standard Subscriptions',
        body: 'Monthly subscriptions may be cancelled at any time. No refund is issued for the current billing period upon cancellation — access continues until the end of the paid period.',
      },
      {
        heading: '3. Annual Subscriptions',
        body: 'Annual subscriptions cancelled within 14 days of payment are eligible for a pro-rated refund of unused months, minus any setup or onboarding costs. No refund is available after 14 days.',
      },
      {
        heading: '4. Service Outages',
        body: 'If the Service is unavailable for more than 24 consecutive hours due to issues on our end, you may request a credit for the affected days. Credits will be applied to your next billing cycle.',
      },
      {
        heading: '5. How to Request a Refund',
        body: 'To request a refund, email support@cuentaiq.com with your account email and the reason for your request. We aim to respond within 3 business days.',
      },
    ],
  },

  dpa: {
    title: 'Data Processing Agreement',
    sections: [
      {
        heading: '1. Purpose',
        body: 'This Data Processing Agreement ("DPA") governs how CuentaIQ processes personal data on behalf of its clients ("Data Controllers") in connection with the Service.',
      },
      {
        heading: '2. Roles',
        body: 'The client acts as the Data Controller. CuentaIQ acts as the Data Processor. CuentaIQ processes personal data only on documented instructions from the client.',
      },
      {
        heading: '3. Types of Data Processed',
        body: 'Data processed may include employee names, contact information, compensation details, tax identification numbers, and other HR or financial records entered into the platform by the client.',
      },
      {
        heading: '4. Sub-processors',
        body: 'CuentaIQ may engage sub-processors (e.g. cloud hosting providers) to assist in delivering the Service. All sub-processors are bound by equivalent data protection obligations.',
      },
      {
        heading: '5. Security Measures',
        body: 'CuentaIQ implements appropriate technical and organisational measures to protect personal data against unauthorised access, loss, or destruction — including encryption, access controls, and regular security reviews.',
      },
      {
        heading: '6. Data Subject Rights',
        body: 'CuentaIQ will assist the client in responding to data subject requests (access, correction, deletion) within the capabilities of the platform.',
      },
      {
        heading: '7. Breach Notification',
        body: 'In the event of a personal data breach, CuentaIQ will notify the client without undue delay and no later than 72 hours after becoming aware, where feasible.',
      },
      {
        heading: '8. Data Return & Deletion',
        body: 'Upon termination of the Service, CuentaIQ will make data available for export for 30 days, after which all personal data will be securely deleted.',
      },
      {
        heading: '9. Applicable Law',
        body: 'This DPA is governed by the Republic Act No. 10173 (Data Privacy Act of 2012) of the Philippines and its Implementing Rules and Regulations.',
      },
      {
        heading: '10. Contact',
        body: 'For data processing inquiries, contact us at hello@cuentaiq.com.',
      },
    ],
  },
};

export default function LegalPage({ type }) {
  const page = PAGES[type];
  if (!page) return null;

  return (
    <LandingLayout>
      <section className="l-section l-section-cream">
        <div className="l-container" style={{ maxWidth: 760 }}>
          <div className="l-section-label">Legal</div>
          <h1 className="l-section-title" style={{ marginTop: 8, fontSize: 36 }}>{page.title}</h1>
          <p style={{ fontSize: 13, color: 'var(--l-ink-mid)', marginTop: 8 }}>Last updated: {LAST_UPDATED}</p>
        </div>
      </section>

      <section className="l-section">
        <div className="l-container" style={{ maxWidth: 760 }}>
          {page.sections.map((s, i) => (
            <div key={i} style={{ marginBottom: 32 }}>
              <h2 style={{ fontFamily: "'DM Serif Display', Georgia, serif", fontSize: 20, color: 'var(--l-ink)', marginBottom: 8 }}>
                {s.heading}
              </h2>
              <p style={{ fontSize: 15, color: 'var(--l-ink-mid)', lineHeight: 1.8 }}>{s.body}</p>
            </div>
          ))}
        </div>
      </section>
    </LandingLayout>
  );
}
